//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Zoomview.rc
//
#define IDR_HTML                        3001
#define IDD_DlgMultiRgnViewProperty     3002
#define IDC_RadioShowData               3003
#define IDC_RadioShowSNRatio            3004
#define IDC_RadioShowRatio              3005
#define IDC_RadioDrawRect               3006
#define IDC_RadioDrawCurve              3007
#define IDC_editSNHighDoor              3008
#define IDC_editSNLowDoor               3009
#define IDC_RadioSeriesSameColor        3010
#define IDC_RadioSeriesDifferentColor   3011
#define IDC_Project                     3012
#define IDC_RadioSortByShotOrder        3013
#define IDC_Area                        3014
#define IDC_RadioSortByShotPoint        3015
#define IDC_Client                      3016
#define IDC_RadioSortByFileNumber       3017
#define IDC_Contractor                  3018
#define IDC_RadioSortByDistance         3019
#define IDC_WorkMonth                   3020
#define IDC_TestDay                     3021
#define IDC_WorkYear                    3022
#define IDC_LineName                    3023
#define IDC_Crew                        3024
#define IDC_ProjectYear                 3025
#define IDC_WorkDay                     3026
#define IDC_TestMonth                   3027
#define IDC_TestYear                    3028
#define IDC_TestHour                    3029
#define IDC_TestMinute                  3030
#define IDC_TestMonth3                  3031
#define IDC_TestSecond                  3032
#define IDR_TEXT_VIEW                   3033
#define IDD_DlgXYZInfo                  3034
#define IDR_MULTIDOC_VIEW               3035
#define IDC_dMinNorth                   3036
#define IDC_dMinEast                    3037
#define IDC_dMinValue                   3038
#define IDC_dMaxNorth                   3039
#define IDC_dMaxEast                    3040
#define IDC_dMaxValue                   3041
#define IDC_dAverNorth                  3042
#define IDC_dAverEast                   3043
#define IDC_dAverValue                  3044
#define IDC_nQuantity                   3045
#define IDC_sOutFile                    3046
#define IDD_ProgressMonitor             3047
#define IDD_DlgPassword                 3048
#define IDB_FHTREE                      3049
#define IDD_AskOneValue                 3050
#define IDD_InfoDlg                     3051
#define IDR_FHZoomViewToolBar           3052
#define IDC_CursorZoomIn                3053
#define IDC_CursorZoomOut               3054
#define IDD_FHZoomAppearance            3055
#define IDR_FHEditViewPopUp             3056
#define IDD_DlgColorModal               3057
#define IDD_FHEditViewSetSize           3058
#define IDD_DlgTreeProperty             3059
#define IDC_Monitor                     3060
#define IDC_sAnswer                     3061
#define CG_IDC_PROGDLG_PROGRESS         3062
#define CG_IDC_PROGDLG_PERCENT          3063
#define CG_IDC_PROGDLG_STATUS           3064
#define IDC_sValue                      3065
#define IDC_sAsk                        3066
#define IDC_EditTitle                   3067
#define IDC_RowNumber                   3068
#define IDC_EditFootString              3069
#define IDC_ColNumber                   3070
#define IDC_nAreaNumber                 3071
#define IDC_nLineNumber                 3072
#define IDC_nTotalLineNumber            3073
#define IDC_sAreaCurrent                3074
#define IDC_FrameThickLineColorHor      3075
#define IDC_FrameThinLineColorHor       3076
#define IDC_nThickLineStartHor          3077
#define IDC_nThinLineStartHor           3078
#define IDC_nThickLineEndHor            3079
#define IDC_nThinLineEndHor             3080
#define IDC_nThickLineStepHor           3081
#define IDC_nThinLineStepHor            3082
#define IDC_CheckUseUserDefineCoor      3083
#define IDC_ButtonCoorThickColorVer     3084
#define IDC_ButtonCoorThinColorVer      3085
#define IDC_FrameThickLineColorVer      3086
#define IDC_FrameThinLineColorVer       3087
#define IDC_nThickLineStartVer          3088
#define IDC_nThinLineStartVer           3089
#define IDC_nThickLineEndVer            3090
#define IDC_nThinLineEndVer             3091
#define IDC_nThickLineStepVer           3092
#define IDC_nThinLineStepVer            3093
#define IDC_ButtonCoorFont              3094
#define IDC_ButtonMapCharFont           3095
#define IDC_CheckDrawCoor               3096
#define IDC_CheckDrawTitle              3097
#define IDC_ButtonCoorThickColorHor     3098
#define IDC_ButtonCoorThinColorHor      3099
#define IDC_ButtonDrawLineColor         3100
#define IDC_ButtonDrawCurrentLineColor  3101
#define IDC_ButtonTitleFont             3102
#define IDC_nStart                      3103
#define IDC_ButtonMapCharCurrFont       3104
#define IDC_MoStatus                    3105
#define IDC_MPROGRESS                   3106
#define IDC_MPERCENT                    3107
#define IDC_nEnd                        3108
#define IDC_Check_AutoDecideFormat      3109
#define IDS_NoLineInArea                3110
#define IDD_AskPage                     3111
#define IDS_AreaMustSelected            3112
#define IDD_ChartProperty               3113
#define IDC_nPageSelected               3114
#define IDS_TopoNetPointQtyError        3115
#define IDR_IDCreator                   3116
#define IDD_DlgAskPage                  3117
#define IDS_LineMustBeSelected          3118
#define IDD_dlgLoadBackGroundPic        3119
#define IDC_SliderCurrentPage           3120
#define IDS_AreaMustBeSelected          3121
#define IDC_radioDimemsion              3122
#define IDC_nPageQty                    3123
#define IDC_RADIO2                      3124
#define IDC_radioDimension2             3125
#define IDC_comboUserLevel              3126
#define IDS_RecordQtyError              3127
#define IDC_checkShowLegend             3128
#define IDC_staticContentColor          3129
#define IDC_checkShowBorder             3130
#define IDC_staticContentCurrColor      3131
#define IDS_ErrorWhenWriteInFile        3132
#define IDC_editContentSize             3133
#define IDS_TreeViewNotFound            3134
#define IDC_EditTitleString             3135
#define IDC_spinContentSize             3136
#define IDD_DlgSprTextImporter          3137
#define IDC_editContentCurrSize         3138
#define IDC_TextShower                  3139
#define IDC_spinContentCurrSize         3140
#define IDC_buttonOpenFile              3141
#define IDC_comboCommonPattern          3142
#define IDD_DlgSeisWorkProperty         3143
#define IDC_comboCurrentPattern         3144
#define IDC_comboSeriesNames            3145
#define IDC_ButtonPath                  3146
#define IDC_staticSeriesColor           3147
#define IDC_editCurrentFile             3148
#define IDC_editCurrentColorBrighter    3149
#define IDC_EditPath                    3150
#define IDC_buttonSeriesColor           3151
#define IDS_UnableOpenFile              3152
#define IDC_LIST1                       3153
#define IDC_listChartType               3154
#define IDC_radioRefPointType           3155
#define IDC_listSprText                 3156
#define IDC_radioRefPointType2          3157
#define IDR_MenuIDCreator               3158
#define IDC_radioRefPointType3          3159
#define IDC_EditArea1                   3160
#define IDC_staticRefPointType          3161
#define IDS_UnableCreateFile            3162
#define IDC_staticDataShowType          3163
#define IDD_DlgNewDataBase              3164
#define IDC_EditArea2                   3165
#define IDD_DlgPasswordAdder            3166
#define IDC_editFileName                3167
#define IDS_TOPONET_FileError           3168
#define IDC_buttonFileName              3169
#define IDC_comboItemName               3170
#define IDC_editWestCoor                3171
#define IDC_EditArea3                   3172
#define IDC_editEastCoor                3173
#define IDS_TOPONET_NotTopoFile         3174
#define IDC_editSouthCoor               3175
#define IDC_checkTab                    3176
#define IDC_editNorthCoor               3177
#define IDS_TOPONET_No2LinkVertexOnLine 3178
#define IDC_checkComma                  3179
#define IDC_checkKeepRatio              3180
#define IDS_TOPONET_No2LineOnTheVertex  3181
#define IDC_checkSemiColon              3182
#define IDC_checkBlank                  3183
#define IDC_checkOther                  3184
#define IDC_Seperator                   3185
#define IDC_editStartLine               3186
#define IDC_editEndLine                 3187
#define IDC_check                       3188
#define IDC_checkColon                  3189
#define IDC_checkVerticalLine           3190
#define IDR_MenuTest                    3191
#define IDR_ACCELERATORFHEDITVIEW       3192
#define IDC_sUserName                   3193
#define IDC_sTip                        3194
#define IDR_HTML_DLGSEARCHGATHER        3195
#define IDC_sDateStart                  3196
#define IDC_sDateEnd                    3197
#define IDV_Accelerator                 3198
#define IDB_Number_0                    3199
#define IDB_Number_1                    3200
#define IDB_Number_2                    3201
#define IDB_Number_3                    3202
#define IDB_Number_4                    3203
#define IDB_Number_5                    3204
#define IDB_Number_6                    3205
#define IDB_Number_7                    3206
#define IDB_Number_8                    3207
#define IDB_Number_9                    3208
#define IDB_Number_Point                3209
#define IDB_Number_Minus                3210
#define ID_FHZoomIn                     35001
#define ID_FHZoomOut                    35003
#define ID_VIEW_STOP                    35004
#define ID_VIEW_REFRESH                 35005
#define ID_VIEW_FONTS_LARGEST           35006
#define ID_VIEW_FONTS_LARGE             35007
#define ID_VIEW_FONTS_MEDIUM            35008
#define ID_VIEW_FONTS_SMALL             35009
#define ID_VIEW_FONTS_SMALLEST          35010
#define ID_GO_BACK                      35011
#define ID_GO_FORWARD                   35012
#define ID_GO_START_PAGE                35013
#define ID_GO_SEARCH                    35014
#define ID_FHEnableInfoWnd              35015
#define ID_FHZoomFull                   35016
#define ID_FHEnableCor                  35017
#define ID_FHSetFont                    35018
#define ID_FHZoomInHor                  35019
#define ID_FHZoomOutHor                 35020
#define ID_FHZoomInVer                  35021
#define ID_FHZoomOutVer                 35022
#define ID_FHZoomErrorMsg               35023
#define ID_FHZoomViewNext               35024
#define ID_FHZoomViewLast               35025
#define ID_FHZoomViewSearch             35026
#define ID_FHZoomViewExportBitmap       35027
#define ID_FHEditViewAddRow             35028
#define ID_FHEditViewAddCol             35029
#define ID_FHEditViewSetSize            35030
#define ID_FHEditViewDelRow             35031
#define ID_FHEditView_DelCol            35032
#define ID_FHEditViewInsRow             35033
#define ID_FHEditViewInsCol             35034
#define ID_FHEditViewUpdateGrid         35035
#define ID_FHTreeOpenDataBase           35036
#define ID_FHTreeDataBaseChangeName     35037
#define ID_FHTreeNewDataBase            35038
#define ID_FHTreeInsertLine             35039
#define ID_FHTreeRemoveLine             35040
#define ID_FHTreeDrawLineData           35041
#define ID_FHTreeDrawLineMap            35042
#define ID_FHTreeInsertArea             35043
#define ID_FHTreeRemoveArea             35044
#define ID_FHTreeDrawAreaMap            35045
#define ID_FHTreeNewLineData            35046
#define ID_FHTreeShowFullName           35047
#define ID_FHTreeShowSortedName         35048
#define ID_FHTreeProperty               35049
#define ID_FHZoomInArea                 35050
#define ID_FHTreeCloseDataBase          35051
#define ID_FHZoomSearch                 35052
#define ID_FHEDITVIEWPOPUP_CUT          35053
#define ID_FHEDITVIEWPOPUP_Paste        35054
#define ID_FHEDITVIEWPOPUP_Copy         35055
#define ID_FHEditView_DelAllSelCol      35056
#define ID_FHEditView_DelAllSelRow      35057
#define ID_FHEditViewReWriteOrder       35058
#define ID_FHEditView_DelAllSameRow     35059
#define ID_FHEDITVIEWPOPUP_BatchEdit    35060
#define ID_ChartProperty                35061
#define ID_FHEditView_MarlAllSameRowWithCols 35062
#define ID_FHEditView_MarlAllSameRowsOnCol 35063
#define ID_EditView_RemoveSameMark      35064
#define ID_FHSettings                   35065
#define ID_SPS_CalcSvSysRays            35067
#define ID_FHAddCurrItemToBaseMap       35068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3197
#define _APS_NEXT_COMMAND_VALUE         35069
#define _APS_NEXT_CONTROL_VALUE         3195
#define _APS_NEXT_SYMED_VALUE           3195
#endif
#endif
